CREATE DATABASE reddit;

use reddit;

CREATE TABLE posts(
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(100) NOT NUll,
url VARCHAR(500) NOT NULL,
timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
score INT NOT NULL DEFAULT 0,
owner VARCHAR(100) NOT NULL,
PRIMARY KEY(id)
);